### ISSUE TITLE
Research and create tutorial for the client side framework

### ISSUE THREAD

**Issue by aggiewb** [nataigna/ITC-134-Group3-ApplicationStack#5]

**Comment by aggiewb** [comment]
Create a txt document to store tutorial and research

**Comment by liyuncc** [comment]
task completed

**Comment by aggiewb** [comment]
#30 #23 #21 #20 #15

**Comment by aggiewb** [comment]
Link to Google doc: https://docs.google.com/document/d/1yJ365uTQ0Nki6CjsZnTdEQj9xrx9YofBquZpKypPzA0/edit?usp=sharing
